### PR TITLE
Refactor folder structure, add setup.py

### PR DESCRIPTION
**Pull request by vanatteveldt**
I moved all packages into a separate folder and created a setup.py script. If you agree with this, could you also push it to pypi to make it easier to install?

### CODE REVIEW

**Comment by rubenIzquierdo** [comment]
This library is not used anymore by any other module.

# 

Ruben Izquierdo Bevia
Vrije University of Amsterdam
ruben.izquierdobevia@vu.nlmailto:ruben.izquierdobevia@vu.nl
http://rubenizquierdobevia.com/

On 19 Apr 2016, at 13:22, Wouter van Atteveldt <notifications@github.com<mailto:notifications@github.com>> wrote:

I moved all packages into a separate folder and created a setup.py script. If you agree with this, could you also push it to pypi to make it easier to install?

---

You can view, comment on, or merge this pull request online at:

  https://github.com/cltl/VUA_pylib/pull/2

Commit Summary
-   Refactor folder structure, add setup.py

File Changes
-   R VUA_pylib/**init**.pyhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-0 (0)
-   R VUA_pylib/common/**init**.pyhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-1 (0)
-   R VUA_pylib/common/common.pyhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-2 (0)
-   R VUA_pylib/corpus_reader/**init**.pyhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-3 (0)
-   R VUA_pylib/corpus_reader/google_web_nl.pyhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-4 (0)
-   R VUA_pylib/io/**init**.pyhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-5 (0)
-   R VUA_pylib/io/feature_file.pyhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-6 (0)
-   R VUA_pylib/lexicon/**init**.pyhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-7 (0)
-   R VUA_pylib/lexicon/data/subjclueslen1-HLTEMNLP05.READMEhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-8 (0)
-   R VUA_pylib/lexicon/data/subjclueslen1-HLTEMNLP05.tffhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-9 (0)
-   R VUA_pylib/lexicon/lexicon.pyhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-10 (0)
-   A setup.pyhttps://github.com/cltl/VUA_pylib/pull/2/files#diff-11 (21)

Patch Links:
-   https://github.com/cltl/VUA_pylib/pull/2.patch
-   https://github.com/cltl/VUA_pylib/pull/2.diff

**Comment by vanatteveldt** [comment]
In that case, shouldn't it be removed as well from https://github.com/cltl/opinion_miner_deluxe? 

And if there is no time, why not accept the pull request and make it a little easier to install the opinion miner?

**Comment by rubenIzquierdo** [comment]
https://github.com/cltl/opinion_miner_deluxe is the old version of the opinion miner which is no longer maintained nor updated. The last version, and which is used in the NWR pipeline is at: https://github.com/rubenIzquierdo/opinion_miner_deluxePP

**Comment by vanatteveldt** [comment]
O ok, in that case I guess I wasted my time :-). Maybe you should put some sort of deprecation message in the opinion_miner_deluxe readme to point to the new version?

**Pull request closed without merging**
